# Generated by Django 3.2.6 on 2021-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.CharField(max_length=2000)),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=4000)),
                ('Difficulty', models.CharField(max_length=100)),
            ],
        ),
    ]
