# Generated by Django 3.2.6 on 2021-08-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=200)),
                ('Output', models.CharField(max_length=200)),
                ('Name2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verdict', models.CharField(max_length=100)),
                ('Submitted', models.DateTimeField(verbose_name='date published')),
                ('Name1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
    ]
