# Generated by Django 3.2.6 on 2021-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0002_solutions_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='Input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Output',
            field=models.TextField(),
        ),
    ]
