# Generated by Django 3.2.6 on 2021-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0003_auto_20211223_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problems',
            name='Statement',
            field=models.TextField(),
        ),
    ]
