# Generated by Django 3.2.6 on 2022-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0004_auto_20211223_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sEmail', models.TextField()),
                ('sName', models.TextField()),
                ('sPassword', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='Submitted',
        ),
    ]
