# Generated by Django 3.2.6 on 2022-05-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0005_auto_20220513_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='sEmail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='sName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='sPassword',
            field=models.CharField(max_length=100),
        ),
    ]
